// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/test.ts";
import * as $3 from "./routes/blog.tsx";
import * as $4 from "./routes/blog/notes/098f6bcd4621d373cade4e832627b4f6.jsx";
import * as $5 from "./routes/blog/notes/116,101,115,116.jsx";
import * as $6 from "./routes/blog/notes/test.jsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/test.ts";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Todo.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/test.ts": $2,
    "./routes/blog.tsx": $3,
    "./routes/blog/notes/098f6bcd4621d373cade4e832627b4f6.jsx": $4,
    "./routes/blog/notes/116,101,115,116.jsx": $5,
    "./routes/blog/notes/test.jsx": $6,
    "./routes/index.tsx": $7,
    "./routes/test.ts": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Todo.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
