// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/api/test.ts";
import * as $3 from "./routes/blog.tsx";
import * as $4 from "./routes/blog/notes/dGVzdA==.jsx";
import * as $5 from "./routes/blog/posts/YQ==.jsx";
import * as $6 from "./routes/blog/posts/Yg==.jsx";
import * as $7 from "./routes/blog/posts/ZnJlc2gg66GcIOqwnOuwnCDruJTroZzqt7gg6rWs7ZiE6riw.jsx";
import * as $8 from "./routes/blog/posts/[slug].tsx";
import * as $9 from "./routes/blog/posts/dGVzdHRlc3Q=.jsx";
import * as $10 from "./routes/blog/posts/dGVzdHRlc3QgY29weQ==.jsx";
import * as $11 from "./routes/blog/posts/dGVzdHRlc3QgY29weSA0.jsx";
import * as $12 from "./routes/blog/posts/dGVzdHRlc3QgY29weSA1.jsx";
import * as $13 from "./routes/blog/posts/dGVzdHRlc3QgY29weSA2.jsx";
import * as $14 from "./routes/blog/posts/dGVzdHRlc3QgY29weSA3.jsx";
import * as $15 from "./routes/blog/posts/dGVzdHRlc3QgY29weSA4.jsx";
import * as $16 from "./routes/blog/posts/dGVzdHRlc3QgY29weSA5.jsx";
import * as $17 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxMA==.jsx";
import * as $18 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxMQ==.jsx";
import * as $19 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxMg==.jsx";
import * as $20 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxMw==.jsx";
import * as $21 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxNA==.jsx";
import * as $22 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxNQ==.jsx";
import * as $23 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxNg==.jsx";
import * as $24 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxNw==.jsx";
import * as $25 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxOA==.jsx";
import * as $26 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAxOQ==.jsx";
import * as $27 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAy.jsx";
import * as $28 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyMA==.jsx";
import * as $29 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyMQ==.jsx";
import * as $30 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyMg==.jsx";
import * as $31 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyMw==.jsx";
import * as $32 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyNA==.jsx";
import * as $33 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyNQ==.jsx";
import * as $34 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyNg==.jsx";
import * as $35 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyNw==.jsx";
import * as $36 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAyOA==.jsx";
import * as $37 from "./routes/blog/posts/dGVzdHRlc3QgY29weSAz.jsx";
import * as $38 from "./routes/index.tsx";
import * as $39 from "./routes/test.ts";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Input.tsx";
import * as $$2 from "./islands/Todo.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/api/test.ts": $2,
    "./routes/blog.tsx": $3,
    "./routes/blog/notes/dGVzdA==.jsx": $4,
    "./routes/blog/posts/YQ==.jsx": $5,
    "./routes/blog/posts/Yg==.jsx": $6,
    "./routes/blog/posts/ZnJlc2gg66GcIOqwnOuwnCDruJTroZzqt7gg6rWs7ZiE6riw.jsx":
      $7,
    "./routes/blog/posts/[slug].tsx": $8,
    "./routes/blog/posts/dGVzdHRlc3Q=.jsx": $9,
    "./routes/blog/posts/dGVzdHRlc3QgY29weQ==.jsx": $10,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSA0.jsx": $11,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSA1.jsx": $12,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSA2.jsx": $13,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSA3.jsx": $14,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSA4.jsx": $15,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSA5.jsx": $16,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxMA==.jsx": $17,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxMQ==.jsx": $18,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxMg==.jsx": $19,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxMw==.jsx": $20,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxNA==.jsx": $21,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxNQ==.jsx": $22,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxNg==.jsx": $23,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxNw==.jsx": $24,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxOA==.jsx": $25,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAxOQ==.jsx": $26,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAy.jsx": $27,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyMA==.jsx": $28,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyMQ==.jsx": $29,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyMg==.jsx": $30,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyMw==.jsx": $31,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyNA==.jsx": $32,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyNQ==.jsx": $33,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyNg==.jsx": $34,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyNw==.jsx": $35,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAyOA==.jsx": $36,
    "./routes/blog/posts/dGVzdHRlc3QgY29weSAz.jsx": $37,
    "./routes/index.tsx": $38,
    "./routes/test.ts": $39,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Input.tsx": $$1,
    "./islands/Todo.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
